#!/bin/bash

# sudo modprobe v4l2loopback devices=2 video_nr="40,42" max_buffers="8" exclusive_caps="1,1"

sudo /home/pi/adversarial-camera/configfs/usb-gadget.sh

/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=20
/usr/bin/v4l2-ctl -c video_bitrate=25000000

# sudo /home/pi/adversarial-camera/src/uvc-gadget -f1 -s2 -r1  -u /dev/video2 -v /dev/video0
